ovgs_secured:
    resource: "@OVGSSecuredBundle/Resources/config/routing.yml"
    prefix:   /secured

ovgs_backoffice:
    resource: "@OVGSBackofficeBundle/Resources/config/routing.yml"
    prefix:   /backoffice

