jms_security_extra:
    secure_all_services: false
    expressions: true

security:
  
    #Configuro el tipo de encriptacion que se utilizara en la entidad
    #encoders:
     #   OVGS\SecuredBundle\Entity\User:
      #      algorithm: sha512
       #     encode-as-base64: true
        #    iterations: 10
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        
    #Configuro los proveedores de usuarios
    providers:
      chain_provider:
          chain:
            providers: [in_memory]
             
            
      in_memory:
          memory:
            users:
              user:  { password: userpass, roles: [ 'ROLE_USER' ] }
              admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }     
              
      #user_db:
       #   entity: { class: OVGSSecuredBundle:User, property: userName }  
                
    #Configuro el cortafuego            
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        #Elimino la seguridad para la pantalla de login
        login:
            pattern:  ^/secured/login$
            security: false
            
        #Configuro el area de seguridad
        secured_area:       
          
            pattern: ^/
            
            form_login:
                check_path: secured_login_check
                login_path: secured_login
                
            logout:
                path:   secured_logout
                target: secured_login
                invalidate_session: false
            
           # http_basic:
            #    realm: "Secured Area"      
    #access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
