parameters:
#    ovgs_backoffice.example.class: OVGS\BackofficeBundle\Example

services:
#    ovgs_backoffice.example:
#        class: %ovgs_backoffice.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
