parameters:
#    ovgs_secured.example.class: OVGS\SecuredBundle\Example

services:
#    ovgs_secured.example:
#        class: %ovgs_secured.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
