parameters:
#    ovgs_test.example.class: OVGS\TestBundle\Example

services:
#    ovgs_test.example:
#        class: %ovgs_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
